myinventory/myinventory/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stock.urls')),
]

myinventory/stock/urls.py
"""Defines URL patterns for learning_logs."""
from django.urls import path
from . import views
app_name = 'stock'
urlpatterns = [
# Home page
path('', views.index, name='index'),
# Page that shows all topics.
path('types/', views.types, name='types'),
# Detail page for a single type.
path('types/<int:type_id>/', views.type, name='type'),
]

myinventory/stock/models.py
from django.db import models

# Create your models here.
class Type(models.Model):
    """A item the user is going to add."""
    Name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
      """Return a string representation of the model."""
      return self.Name

class Item(models.Model):
   """Something specific to add to the item category."""
   item = models.ForeignKey(Type, on_delete=models.CASCADE)
   Name = models.TextField()
   date_added = models.DateTimeField(auto_now_add=True)

   
class Meta:
   verbose_name_plural = 'Items'
def __str__(self):
   """Return a string representation of the model."""
   return f"{self.Name[:50]}..."

myinventory/stock/views.py
from django.shortcuts import render
from .models import Type, Item
# Create your views here.

def index(request):
    """The home page for Stock."""
    return render(request, 'stock/index.html')


def types(request):
    """Show all items."""
    types = Type.objects.order_by('date_added')
    context = {'types': types}
    return render(request, 'stock/types.html', context)


def type(request, type_id):
    """Show a single topic and all its entries."""
    type = Type.objects.get(id=type_id)
    items = type.item_set.order_by('-date_added')
    context = {'type': type, 'items': items}
    return render(request, 'stock/type.html', context)

myinventory/stock/templates/stock/base.html
<head>
    {% load static %}
    <link rel="stylesheet"  href="{% static 'css/style.css'  %}">
  </head>

<p>
    <a href="{% url 'stock:index' %}">Stock Inventory</a> -
    <a href="{% url 'stock:types' %}">My Items</a>
</p>
    {% block content %}{% endblock content %}

myinventory/stock/templates/stock/index.html
{% extends "stock/base.html" %}
{% block content %}

<p>Stock Check</p>
<p>Stock Check helps you keep track of your stock, for any items you're
looking for.</p>

{% endblock content %}

myinventory/stock/templates/stock/type.html
{% extends 'stock/base.html' %}
{% block content %}
<p>Type: {{ type }}</p>


<p>Items:</p>
<ul>
     {% for item in items %}
    <li>
 <p>{{ item.date_added|date:'M d, Y H:i' }}</p>
 <p>{{ item.Name|linebreaks }}</p>
    </li>
     {% empty %}
    <li>There are no types for this item yet.</li>
    {% endfor %}
    </ul>
    {% endblock content %}

myinventory/stock/templates/stock/types.html
{% extends "stock/base.html" %}
{% block content %}
<p>Type</p>
 <ul>
 {% for type in types %}
 <li> <a href="{% url 'stock:type' type.id %}">{{ type }}</a>
    </li>
 {% empty %}
<li>No types have been added yet.</li>
 {% endfor %}
 </ul>
{% endblock content %}